app = "simpleprint"
primary_region = "yyz"

[env]
NODE_ENV = "production"
PORT = "3080"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3080
min_machines_running = 1

[[mounts]]
destination = "/app/data"
source = "simpleprint_data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
